export const groupData = [
  {
    id: 1,
    grpName: 'John Wick',
    image: '/images/1.jpg',
    dateTime: new Date(),
    messages: [
      { sender: 'John Wick', msg: 'Hey, are we on schedule?' },
      { sender: 'You', msg: 'Yes, all good from my side.' },
      { sender: 'John Wick', msg: 'Great, keep me updated.' },
      { sender: 'You', msg: 'Sure thing!' },
      { sender: 'John Wick', msg: 'Let me know if anything changes.' },
      { sender: 'John Wick', msg: 'All clear so far.' },
      { sender: 'You', msg: 'Confirmed, nothing pending.' },
      { sender: 'John Wick', msg: 'Perfect.' },
      { sender: 'You', msg: 'Ping me if you need anything else.' },
      { sender: 'John Wick', msg: 'Will do.' },
    ],
  },
  {
    id: 2,
    grpName: 'Language Pod',
    dateTime: new Date('2024-07-02T15:30:00'),
    messages: [
      { sender: 'Alice', msg: 'Did you check the new module?' },
      { sender: 'You', msg: 'Yes, I reviewed it.' },
      { sender: 'Alice', msg: 'Found any gaps?' },
      { sender: 'You', msg: 'Minor alignment issues.' },
      { sender: 'Alice', msg: 'Okay, I will fix those.' },
      { sender: 'You', msg: 'Great, thanks!' },
      { sender: 'Alice', msg: 'Any other concerns?' },
      { sender: 'You', msg: 'Looks good overall.' },
      { sender: 'Alice', msg: 'I’ll inform the team.' },
      { sender: 'You', msg: 'Perfect.' },
    ],
  },
  {
    id: 3,
    grpName: 'Assessify Team',
    image: '/images/2.jpg',
    dateTime: new Date('2024-07-01T10:15:00'),
    messages: [
      { sender: 'David', msg: 'Deadline is next week.' },
      { sender: 'You', msg: 'Noted. Preparing reports.' },
      { sender: 'David', msg: 'Please focus on test coverage.' },
      { sender: 'You', msg: 'Test cases in progress.' },
      { sender: 'David', msg: 'Great, ping me when done.' },
      { sender: 'You', msg: 'Will do.' },
      { sender: 'David', msg: 'Review meeting tomorrow.' },
      { sender: 'You', msg: 'Calendar invite received.' },
      { sender: 'David', msg: 'Thanks!' },
      { sender: 'You', msg: 'All set.' },
    ],
  },
  {
    id: 4,
    grpName: 'React Developers',
    dateTime: new Date(),
    messages: [
      { sender: 'Sophia', msg: 'New version of React is out.' },
      { sender: 'You', msg: 'Yes, I saw the release notes.' },
      { sender: 'Sophia', msg: 'Major updates in hooks.' },
      { sender: 'You', msg: 'Looks promising.' },
      { sender: 'Sophia', msg: 'We should plan migration soon.' },
      { sender: 'You', msg: 'Agreed, will create a task.' },
      { sender: 'Sophia', msg: 'Testing is important.' },
      { sender: 'You', msg: 'Let’s allocate time for that.' },
      { sender: 'Sophia', msg: 'Perfect, thanks!' },
      { sender: 'You', msg: 'On it.' },
    ],
  },
  {
    id: 5,
    grpName: 'Product Design',
    image: '/images/3.jpg',
    dateTime: new Date('2024-07-01T11:00:00'),
    messages: [
      { sender: 'Ethan', msg: 'The UI draft is ready.' },
      { sender: 'You', msg: 'I will check it now.' },
      { sender: 'Ethan', msg: 'Looking forward to feedback.' },
      { sender: 'You', msg: 'Reviewing, give me a moment.' },
      { sender: 'Ethan', msg: 'Sure.' },
      { sender: 'You', msg: 'Color palette is nice.' },
      { sender: 'Ethan', msg: 'Thanks, worked hard on that.' },
      { sender: 'You', msg: 'Typography could improve.' },
      { sender: 'Ethan', msg: 'Noted.' },
      { sender: 'You', msg: 'Will share full notes by EOD.' },
    ],
  },
  {
    id: 6,
    grpName: 'QA Team',
    dateTime: new Date('2024-06-30T17:00:00'),
    messages: [
      { sender: 'Olivia', msg: 'Bugs reported on login.' },
      { sender: 'You', msg: 'Checking logs now.' },
      { sender: 'Olivia', msg: 'Reproducible on mobile too.' },
      { sender: 'You', msg: 'Got it, will fix.' },
      { sender: 'Olivia', msg: 'Ping me once done.' },
      { sender: 'You', msg: 'ETA is 30 minutes.' },
      { sender: 'Olivia', msg: 'Cool, thanks!' },
      { sender: 'You', msg: 'Pushed the fix.' },
      { sender: 'Olivia', msg: 'Verified, working fine.' },
      { sender: 'You', msg: 'Closing the ticket.' },
    ],
  },
  {
    id: 7,
    grpName: 'Mobile Team',
    image: '/images/4.jpg',
    dateTime: new Date('2024-07-02T09:45:00'),
    messages: [
      { sender: 'Liam', msg: 'Android build failing.' },
      { sender: 'You', msg: 'Checking CI logs.' },
      { sender: 'Liam', msg: 'Possible dependency mismatch.' },
      { sender: 'You', msg: 'Investigating.' },
      { sender: 'Liam', msg: 'Let me know progress.' },
      { sender: 'You', msg: 'Issue found, fixing now.' },
      { sender: 'Liam', msg: 'Thanks for the update.' },
      { sender: 'You', msg: 'Fix deployed.' },
      { sender: 'Liam', msg: 'Re-running build.' },
      { sender: 'You', msg: 'Confirmed working.' },
    ],
  },
  {
    id: 8,
    grpName: 'Marketing Group',
    dateTime: new Date('2024-07-01T14:00:00'),
    messages: [
      { sender: 'Emma', msg: 'Campaign goes live tomorrow.' },
      { sender: 'You', msg: 'All assets are ready.' },
      { sender: 'Emma', msg: 'Briefed the team.' },
      { sender: 'You', msg: 'Everything is set.' },
      { sender: 'Emma', msg: 'Tested all flows.' },
      { sender: 'You', msg: 'Good job.' },
      { sender: 'Emma', msg: 'Let’s monitor closely.' },
      { sender: 'You', msg: 'On standby.' },
      { sender: 'Emma', msg: 'Thank you!' },
      { sender: 'You', msg: 'My pleasure.' },
    ],
  },
  {
    id: 9,
    grpName: 'Client Discussion',
    dateTime: new Date('2024-07-02T13:00:00'),
    messages: [
      { sender: 'Client', msg: 'Need proposal update.' },
      { sender: 'You', msg: 'Sending shortly.' },
      { sender: 'Client', msg: 'Add timeline changes.' },
      { sender: 'You', msg: 'Will revise accordingly.' },
      { sender: 'Client', msg: 'Share by today.' },
      { sender: 'You', msg: 'Understood.' },
      { sender: 'Client', msg: 'Thanks.' },
      { sender: 'You', msg: 'File sent, please review.' },
      { sender: 'Client', msg: 'Received, checking.' },
      { sender: 'You', msg: 'Available for any questions.' },
    ],
  },
  {
    id: 10,
    grpName: 'Founders Group',
    image: '/images/5.jpg',
    dateTime: new Date(),
    messages: [
      { sender: 'Founder 1', msg: 'Let’s sync at 5 PM.' },
      { sender: 'You', msg: 'Noted, calendar invite sent.' },
      { sender: 'Founder 2', msg: 'Discuss roadmap.' },
      { sender: 'You', msg: 'Preparing slides.' },
      { sender: 'Founder 1', msg: 'Focus on revenue stream.' },
      { sender: 'You', msg: 'Included projections.' },
      { sender: 'Founder 2', msg: 'Thanks.' },
      { sender: 'You', msg: 'See you at 5.' },
      { sender: 'Founder 1', msg: 'All aligned.' },
      { sender: 'You', msg: 'Ready for the meeting.' },
    ],
  },
];
